name: Attractor

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Attractor
      uses: julianrubisch/attractor-action@add-base-setup
      with:
        version: 'latest'
        bundle: 'false'
        file_prefix: ''
        javascript: 'false'
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: attractor
        path: attractor_output/
